trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CopyFiles@2
    displayName: "Copy EC source code"
    inputs:
      SourceFolder: .
      TargetFolder: '$(build.artifactstagingdirectory)/ecdeploy'

  - task: GoTool@0
    inputs:
      version : '1.17.3'

  - task: Bash@3
    displayName: "Compile source code"
    inputs:
      targetType: 'inline'
      workingDirectory: '$(build.artifactstagingdirectory)/ecdeploy/'
      script: |
        make version && \
        mkdir -p $(build.artifactstagingdirectory)/ecdeploy/bin
        mv ec $(build.artifactstagingdirectory)/ecdeploy/bin

  - task: PublishBuildArtifacts@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master') # only publish artifacts if this is built from the main branch
    displayName: "Publish Terraform files"
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'core'
      
