trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: stg_dir
    value: "$(build.artifactstagingdirectory)/ecdepoy" 

steps:
  - task: CopyFiles@2
    displayName: "Copy EC source code"
    inputs:
      SourceFolder: .
      TargetFolder: '$(stg_dir)'

  - script: python -m pip install -r modules/requirements.txt
    displayName: "Install Dependencies"

  - task: GoTool@0
    inputs:
      version : '1.19.*'

  - task: Bash@3
    displayName: "Testing Code"
    inputs:
      targetType: 'inline'
      workingDirectory: '$(stg_dir)'
      script: |
        go test ./... -v 

  - task: Bash@3
    displayName: "Compiling Deployment Engine"
    inputs:
      targetType: 'inline'
      workingDirectory: '$(stg_dir)'
      script: |
        bash ./scripts/build.sh 

  - task: PublishBuildArtifacts@1
    displayName: "Publish binary"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      PathtoPublish: '$(stg_dir)/bin'
      ArtifactName: 'core'
      
